### ISSUE TITLE
What is the ColoredBox widget in list_tile_selected_background_colored_box.dart

### ISSUE THREAD

**Issue by Lars-** [mono0926/flutter_mono_kit#5]
Hi, I like what you're doing here! 
Unfortunately I found a problem, the widget ColoredBox is undefined.

Can you provide that code as well?

**Comment by mono0926** [comment]
`ListTileSelectedBackgroundColoredBox` is release as [dev version](https://pub.dev/packages/mono_kit/versions/0.14.0-dev+52), so I use Flutter dev channel feature.

ColoredBox is single purpose widget for coloring, but it haven’t shipped as stable channel.
But you can use by changing ColoredBox to  Container 👌
